/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    CounterContract: {
      address:
        "0x4655698a783dbae246985b3ff7bb467e4f824d1bccafd2ba6951831f4ddbecc",
      abi: [
        {
          type: "impl",
          name: "ImplCounter",
          interface_name: "contracts::counter::ICounter",
        },
        {
          type: "interface",
          name: "contracts::counter::ICounter",
          items: [
            {
              type: "function",
              name: "get_counter",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "increase_counter",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "decrease_counter",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "enum",
          name: "contracts::counter::CounterContract::ChangeReason",
          variants: [
            {
              name: "Increase",
              type: "()",
            },
            {
              name: "Decrease",
              type: "()",
            },
            {
              name: "Reset",
              type: "()",
            },
            {
              name: "Set",
              type: "()",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::counter::CounterContract::CounterChanged",
          kind: "struct",
          members: [
            {
              name: "caller",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "old_value",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "new_value",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "reason",
              type: "contracts::counter::CounterContract::ChangeReason",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::counter::CounterContract::Event",
          kind: "enum",
          variants: [
            {
              name: "CounterChanged",
              type: "contracts::counter::CounterContract::CounterChanged",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x304bf1022476e9c168ac02aa10c839c8abdb9ec7d01f7d9aeb474822647d78c",
    },
  },
} as const;

export default deployedContracts;
