[package]
name = "contracts"
version = "0.2.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.12.0"
openzeppelin_access = ">=2.0.0"
openzeppelin_token = ">=2.0.0"

[dev-dependencies]
openzeppelin_utils = ">=2.0.0"
openzeppelin_testing = ">=4.6.0"
snforge_std = ">=0.49.0"

[[target.starknet-contract]]
casm = true

[tool.scarb]
allow-prebuilt-plugins = [
	"snforge_std",
]

[tool.fmt]
sort-module-level-items = true

# Network configurations
[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
block_id.tag = "latest"

# Sepolia network configuration for sncast
[tool.sncast.sepolia]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
account = "sepolia_account"